-- MySQL Script generated by MySQL Workbench
-- Sat Apr  4 02:23:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concert_companion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concert_companion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concert_companion` ;
USE `concert_companion` ;

-- -----------------------------------------------------
-- Table `concert_companion`.`Venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concert_companion`.`Venue` ;

CREATE TABLE IF NOT EXISTS `concert_companion`.`Venue` (
  `idVenue` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Password` CHAR(60) NULL,
  `VenueName` VARCHAR(45) NULL,
  PRIMARY KEY (`idVenue`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concert_companion`.`Concert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concert_companion`.`Concert` ;

CREATE TABLE IF NOT EXISTS `concert_companion`.`Concert` (
  `idConcert` INT NOT NULL AUTO_INCREMENT,
  `ConcertName` VARCHAR(45) NULL,
  `StartDate` BIGINT NOT NULL,
  `EndDate` BIGINT NOT NULL,
  `LightColor` INT NULL,
  `idVenue` INT NOT NULL,
  `LightMode` INT NULL,
  PRIMARY KEY (`idConcert`, `idVenue`),
  INDEX `fk_Concert_Venue_idx` (`idVenue` ASC) VISIBLE,
  CONSTRAINT `fk_Concert_Venue`
    FOREIGN KEY (`idVenue`)
    REFERENCES `concert_companion`.`Venue` (`idVenue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concert_companion`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concert_companion`.`User` ;

CREATE TABLE IF NOT EXISTS `concert_companion`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `PhoneNumber` VARCHAR(13) NOT NULL,
  `ScreenName` VARCHAR(20) NOT NULL,
  `Banned` VARCHAR(45) NULL,
  `idConcert` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idConcert`),
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC) VISIBLE,
  UNIQUE INDEX `ScreenName_UNIQUE` (`ScreenName` ASC) VISIBLE,
  INDEX `fk_User_Concert1_idx` (`idConcert` ASC) VISIBLE,
  CONSTRAINT `fk_User_Concert1`
    FOREIGN KEY (`idConcert`)
    REFERENCES `concert_companion`.`Concert` (`idConcert`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concert_companion`.`Upvotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concert_companion`.`Upvotes` ;

CREATE TABLE IF NOT EXISTS `concert_companion`.`Upvotes` (
  `idUser` INT NOT NULL,
  `idChatMessage` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idChatMessage`),
  CONSTRAINT `fk_Upvotes_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `concert_companion`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concert_companion`.`ChatMessage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concert_companion`.`ChatMessage` ;

CREATE TABLE IF NOT EXISTS `concert_companion`.`ChatMessage` (
  `idChatMessage` INT NOT NULL AUTO_INCREMENT,
  `Message` VARCHAR(45) NULL,
  `idUser` INT NOT NULL,
  `idConcert` INT NOT NULL,
  `Sent` DATETIME NULL,
  `Type` INT NOT NULL,
  `Upvotes_User_idUser` INT NOT NULL,
  PRIMARY KEY (`idChatMessage`, `idUser`, `idConcert`, `Upvotes_User_idUser`),
  INDEX `fk_ChatMessage_User1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_ChatMessage_Concert1_idx` (`idConcert` ASC) VISIBLE,
  INDEX `fk_ChatMessage_Upvotes1_idx` (`Upvotes_User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_ChatMessage_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `concert_companion`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChatMessage_Concert1`
    FOREIGN KEY (`idConcert`)
    REFERENCES `concert_companion`.`Concert` (`idConcert`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChatMessage_Upvotes1`
    FOREIGN KEY (`Upvotes_User_idUser`)
    REFERENCES `concert_companion`.`Upvotes` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
